image: docker:latest

stages:
  - build
  - deploy

build_test:
  stage: build
  before_script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --no-cache --build-arg BACKEND_URL="$TEST_BACKEND_URL" --build-arg ACKEE_KEY="$TEST_ACKEE_KEY" --build-arg ACKEE_URL="$ACKEE_URL" 
      -t $CI_REGISTRY/snynu/frontend-react/test:${CI_COMMIT_SHA} -t $CI_REGISTRY/snynu/frontend-react/test:latest .
    - docker push $CI_REGISTRY/snynu/frontend-react/test:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY/snynu/frontend-react/test:latest
    - echo "built image $CI_REGISTRY/snynu/frontend-react/test:${CI_COMMIT_SHA}"
  only:
    - develop

build_production:
  stage: build
  before_script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --no-cache --build-arg BACKEND_URL="$BACKEND_URL" --build-arg ACKEE_KEY="$ACKEE_KEY" --build-arg ACKEE_URL="$ACKEE_URL"
      -t $CI_REGISTRY/snynu/frontend-react:${CI_COMMIT_SHA} -t $CI_REGISTRY/snynu/frontend-react:latest .
    - docker push $CI_REGISTRY/snynu/frontend-react:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY/snynu/frontend-react:latest
    - echo "built image $CI_REGISTRY/snynu/frontend-react:${CI_COMMIT_SHA}"
  only:
    - master
    
deploy_test:
  stage: deploy
  before_script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" $CI_REGISTRY
  script:
    - echo "deploy image $CI_REGISTRY/snynu/frontend-react/test:${CI_COMMIT_SHA}"
    - docker service update --image $CI_REGISTRY/snynu/frontend-react/test:${CI_COMMIT_SHA} snynu_frontend-test
  only:
    - develop

deploy_production:
  stage: deploy
  before_script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" $CI_REGISTRY
  script:
    - echo "deploy image $CI_REGISTRY/snynu/frontend-react:${CI_COMMIT_SHA}"
    - docker service update --image $CI_REGISTRY/snynu/frontend-react:${CI_COMMIT_SHA} snynu_frontend
  only:
    - master
